from pathlib import Path

OUTPUT_PATH = Path("docs/Opal_Master_Prompt_CLMS.md")
DDL_PATH = Path("scripts/extracted_ddl.sql")

ddl_text = DDL_PATH.read_text(encoding="utf-8").rstrip("\n")

parts: list[str] = []
add = parts.append

add("# OPAL PROMPT — Centralized Litigation Management (CLMS)")
add("")
add("## Index")
add("- [A. Product Vision](#a-product-vision)")
add("- [B. Canonical Data Model](#b-canonical-data-model)")
add("  - [B1. Entity Table](#b1-entity-table)")
add("  - [B2. Machine-Readable Schema](#b2-machine-readable-schema-authoritative)")
add("- [C. RBAC & Security](#c-rbac--security)")
add("- [D. Validations](#d-validations)")
add("- [E. Workflows](#e-workflows)")
add("- [F. UI/UX — Screens](#f-uiux--screens)")
add("- [G. APIs & Integrations](#g-apis--integrations)")
add("- [H. Non-Functional Requirements](#h-non-functional-requirements)")
add("- [I. DevOps & Deployment](#i-devops--deployment)")
add("- [J. Data Import/Export](#j-data-importexport)")
add("- [K. Gaps & Assumptions](#k-gaps--assumptions)")
add("- [Appendix — Mermaid ERD](#appendix--mermaid-erd)")
add("- [Appendix — Roles × Permissions](#appendix--roles--permissions)")
add("- [Appendix — Screen Inventory](#appendix--screen-inventory)")
add("- [Appendix — Authoritative DDL](#appendix--authoritative-ddl)")
add("- [Acceptance Checklist](#acceptance-checklist)")
add("")

add("### A. Product Vision")
add("- Deliver a centralized bilingual (English/Arabic with RTL) litigation management platform for a single law firm in Egypt (timezone Africa/Cairo), replacing legacy MS Access spreadsheets with a secure web system.")
add("- Support end-to-end case lifecycle (clients, matters, hearings, documents, administrative tasks) with enterprise controls: RBAC, audit logging, signed downloads, restorable trash, and rigorous data migration tooling.")
add("- Operate on Laravel 10.49.1, PHP 8.4, MySQL 9.1.0, Bootstrap 5, while remaining compatible with GoDaddy-style shared hosting constraints and future integrations (Outlook, SMS, billing).")
add("")

add("### B. Canonical Data Model")
add("")
add("#### B1. Entity Table")
add("| Entity | Purpose | Key Fields | Required | Unique | Relations |")
add("|---|---|---|---|---|---|")
add("| Client | Organization or individual retaining the firm | client_name_ar, client_name_en, status_id, contact_lawyer_id | client_name_(ar or en), status_id | client_code | 1..n cases, contacts, engagement_letters, power_of_attorneys, documents |")
add("| Case | Litigated matter with full lifecycle metadata | client_id, matter_name_ar, matter_name_en, matter_status_id, court_id, opponent refs | client_id, matter_name_(ar or en) | id (legacy), optional engagement_letter_no | n..m opponents via case_opponents, 1..n hearings, admin_tasks, documents |")
add("| Hearing | Court session scheduled within a case | matter_id, date, decision, next_hearing | matter_id, date | — | belongs to case, optional lawyer |")
add("| AdminTask | Administrative follow-up linked to case | matter_id, required_work, status | matter_id | — | has many admin_subtasks, optional lawyer |")
add("| AdminSubtask | Granular task step | task_id, performer | task_id | — | belongs to admin_task |")
add("| ClientDocument | Metadata for physical/digital documents | client_id, document_storage_type, document_type, deposit_date | client_id, document_storage_type, deposit_date | — | belongs to client, optional case |")
add("| Lawyer | Firm lawyer/staff profile | lawyer_name_ar/en, title_id | lawyer_name_(ar or en) | — | assigned to hearings, tasks, partner on cases |")
add("| Opponent | Counterparty directory | opponent_name_ar/en, is_active | — | — | n..m cases via case_opponents |")
add("| CaseOpponent | Pivot mapping opponents to cases | case_id, opponent_id, capacity_id, is_primary | case_id, opponent_id | — | belongs to case & opponent |")
add("| OptionSet/OptionValue | Lookup catalogs (statuses, capacities, circuits) | key, name_en/ar; code, label_en/ar | key; set_id, code | key | referenced by many FKs |")
add("| DeletionBundle | Trash snapshot root | id (UUID), root_type, root_id, snapshot_json | root_type, root_id, snapshot_json | id | has many deletion_bundle_items |")
add("| DeletionBundleItem | Snapshot entry in bundle | bundle_id, model, payload_json | bundle_id, model | id | belongs to deletion_bundle |")
add("| ImportSession | Tracks ETL runs | session_id, table_name, status | session_id, table_name, status | session_id | has many import_choices |")
add("| EngagementLetter | Fee agreement | client_id, contract_date, status | client_id | — | optional 1..n cases |")
add("| PowerOfAttorney | POA record | client_id, principal_name | client_id, principal_name | — | belongs to client |")
add("| Contact | Client contact person | client_id, email | client_id | — | belongs to client |")
add("")

add("#### B2. Machine-Readable Schema (authoritative)")
add("```sql")
add(ddl_text)
add("```")
add("")

add("### C. RBAC & Security")
add("- Roles: super_admin, admin, lawyer, staff, client_portal. Super admin manages users/roles, trash lifecycle, imports, audits; admin mirrors minus user/role management; lawyer/staff handle casework; client_portal reserved for future read-only portal.")
add("- Permissions: cases.*, hearings.*, documents.view/upload/edit/delete, clients.*, trash.view/restore/purge, import.view/create/execute/cancel/delete/view_template, export.view/create/download, admin.users.manage, admin.roles.manage, admin.audit.view, admin.tools.manage, cases.opponents.view/edit/attach/detach.")
add("- Enforce middleware per route and policies on controllers; document downloads use signed routes. Activity logging (Spatie) captures CRUD/trash actions with causer metadata. Sessions protected via CSRF, login throttling, secure cookies; timeout 120 minutes.")
add("- Trash system snapshots deletions into JSON bundles (TTL 90 days) with dry-run restore and conflict strategies (skip, overwrite, new_copy) plus CLI tooling (`trash:list`, `trash:restore`, `trash:purge`).")
add("- Secrets via `.env`; document uploads constrained to 10 MB MIME whitelist. Plan for future 2FA, IP whitelisting, penetration testing, antivirus scanning.")
add("")

add("### D. Validations")
add("- ClientRequest: bilingual name requirement (`required_without`), unique client_code, numeric mfiles_id, chronological client_start/client_end, logo image ≤2 MB.")
add("- CaseRequest: require client_id and one of matter_name_ar/en; validate numerous lookup FKs (`exists:option_values,id`); ensure date sequencing and non-negative monetary amounts; opponent/court references validated.")
add("- HearingRequest: require matter_id exists, hearing date, `next_hearing` ≥ date, boolean report/notify flags.")
add("- LawyerRequest: require at least one localized name, optional title lookup, email format.")
add("- DocumentUploadRequest: enforce storage_type, conditional file upload with MIME/size cap, mfiles_id when flagged, client exists/matter optional.")
add("- AdminTask/Subtask Requests: validate parent existence, date fields, boolean flags.")
add("- EngagementLetter, PowerOfAttorney, Contact, Court, Opponent Requests: enforce foreign keys, numeric ranges, email/URL validation, localized names.")
add("")

add("### E. Workflows")
add("- Case lifecycle: intake client → create case → attach opponents (`case_opponents`) → schedule hearings → log admin tasks/subtasks → upload documents → adjust status/importance → close or delete (trash bundle).")
add("- Document lifecycle: upload (validate storage type) → store metadata and file under `public/uploads/` → serve via signed download/inline if permitted → deletion retains bundle until purge.")
add("- Trash lifecycle: soft delete triggers bundle with cascade graph; admins review `/trash`, run dry-run, restore with chosen strategy, or purge. CLI mirrors UI; cron for TTL purge planned.")
add("- ETL pipeline: upload Access export → map columns → resolve lookups (choices persisted) → preflight validation (reject logs) → execute import logging counts; templates regenerated via artisan commands.")
add("- Data quality dashboard: metrics for counts, referential integrity, completeness guiding remediation.")
add("")

add("### F. UI/UX — Screens")
add("- Bootstrap 5 layout with locale switcher (`/locale/{locale}`) toggling EN/AR + RTL; tables paginated (~20 rows) with status badges; forms mirror validation rules with localized labels.")
add("- Core screens: dashboard, clients CRUD, case detail tabs (hearings, tasks, documents, opponents), hearings index, document repository/upload, admin tasks/subtasks, import wizard (upload→mapping→choices→preflight→run), template downloads, trash manager, data-quality dashboard, audit logs, courts, opponents, option sets admin, import profiles.")
add("")

add("### G. APIs & Integrations")
add("- Web routes cover CRUD modules, import flows, trash management, signed document downloads, locale switching.")
add("- API currently exposes `GET /api/user` via Sanctum; Opal implementation must design additional REST endpoints for cases, hearings, documents, imports.")
add("- Integrations: M-Files metadata capture, Excel/CSV import (Laravel Excel), GoDaddy-compatible file storage. Planned: Outlook/Exchange calendar sync, SMS gateway, LawPay billing, per-user rate limiting.")
add("")

add("### H. Non-Functional Requirements")
add("- Performance: target <2s page loads; indexes on `cases`, `hearings`, `admin_tasks`, `client_documents`; eager load relationships.")
add("- Reliability: Soft deletes + deletion bundles; restore transactions with conflict reporting; manual TTL purge (cron planned).")
add("- Security: RBAC enforcement, signed downloads, audit logging, CSRF, login throttling; roadmap for 2FA, IP whitelisting, pen tests, antivirus scanning.")
add("- Localization & RTL: EN/AR parity, RTL layout, UTF-8 data, bilingual lookup labels.")
add("- Accessibility: Screen-reader friendly dashboard per checklist; leverage semantic Bootstrap components.")
add("- Hosting constraints: Single-tenant, shared hosting (no storage symlink), PHP 8.4, MySQL 9.1.0, `public/uploads/` storage.")
add("")

add("### I. DevOps & Deployment")
add("- Setup: `composer install`, `npm install && npm run build`, copy `.env`, `php artisan key:generate`, `php artisan migrate:fresh --seed`.")
add("- Environments: local WAMP; staging/production planned on Linux with hardened MySQL and backup automation.")
add("- Queues/Schedule: none active; implement cron for trash purge, backups, audit exports.")
add("- CLI toolkit: `import:*`, template generators, trash commands, opponent normalization, data-quality reports.")
add("- File permissions: ensure `public/uploads/` and storage subdirectories writable (755); secrets in `.env`.")
add("")

add("### J. Data Import/Export")
add("- Sources: Access exports in `Access_Data_Export/` (clients, cases, opponents, tasks, hearings, documents, etc.).")
add("- Import wizard: upload → mapping → choice resolution (fuzzy matching) → preflight → execution; metrics stored in `import_sessions`, rejects logged.")
add("- Templates: Standard/extended case templates, case opponent companion, hearings templates downloadable via routes or artisan commands.")
add("- Exports: Audit log CSV available; plan data-quality exports and functional entity exports.")
add("- Idempotency: Upserts + persisted mapping choices enable reruns; manual remediation for rejects. CSV templates use UTF-8 with Arabic labels.")
add("")

add("### K. Gaps & Assumptions")
add("- No automated cron jobs yet (trash purge, backups, notifications) — schedule in Opal implementation.")
add("- REST API beyond `/api/user` absent — design full API contracts.")
add("- Finance/billing modules referenced in roadmap missing — scope for future phase.")
add("- Antivirus scanning for documents absent — integrate as needed.")
add("- System is single-tenant; multi-tenant requirements would need redesign.")
add("- Import pipeline assumes Access files conform to templates; automated retries lacking.")
add("- Court/circuit lookup data seeded from legacy exports; validate completeness with stakeholders.")
add("")

add("### Appendix — Mermaid ERD")
add("```mermaid")
add("erDiagram")
add("    CLIENTS ||--o{ CASES : has")
add("    CLIENTS ||--o{ CONTACTS : has")
add("    CLIENTS ||--o{ ENGAGEMENT_LETTERS : has")
add("    CLIENTS ||--o{ POWER_OF_ATTORNEYS : has")
add("    CLIENTS ||--o{ CLIENT_DOCUMENTS : has")
add("    CLIENTS ||--o{ IMPORT_SESSIONS : seeds")
add("")
add("    CASES }o--|| CLIENTS : belongs_to")
add("    CASES ||--o{ HEARINGS : has")
add("    CASES ||--o{ ADMIN_TASKS : has")
add("    CASES ||--o{ CLIENT_DOCUMENTS : has")
add("    CASES ||--o{ CASE_OPPONENTS : has")
add("    CASES }o--|| ENGAGEMENT_LETTERS : optional_contract")
add("    CASES }o--o| COURTS : venue")
add("    CASES }o--o| LAWYERS : partner")
add("    CASES }o--o| OPTION_VALUES : status_category_degree_importance_branch_capacity")
add("")
add("    CASE_OPPONENTS }o--|| CASES : case")
add("    CASE_OPPONENTS }o--|| OPPONENTS : opponent")
add("    CASE_OPPONENTS }o--o| OPTION_VALUES : capacity")
add("")
add("    HEARINGS }o--|| CASES : belongs_to")
add("    HEARINGS }o--o| LAWYERS : assigned")
add("")
add("    ADMIN_TASKS }o--|| CASES : belongs_to")
add("    ADMIN_TASKS }o--o| LAWYERS : assigned")
add("    ADMIN_TASKS ||--o{ ADMIN_SUBTASKS : has")
add("")
add("    ADMIN_SUBTASKS }o--|| ADMIN_TASKS : belongs_to")
add("    ADMIN_SUBTASKS }o--o| LAWYERS : assigned")
add("")
add("    CLIENT_DOCUMENTS }o--|| CLIENTS : belongs_to")
add("    CLIENT_DOCUMENTS }o--o| CASES : optional_case")
add("    CLIENT_DOCUMENTS }o--o| USERS : uploaded_by")
add("")
add("    DELETION_BUNDLES ||--o{ DELETION_BUNDLE_ITEMS : contains")
add("    DELETION_BUNDLES }o--o| USERS : deleted_by")
add("")
add("    USERS ||--o{ MODEL_HAS_ROLES : role_assignment")
add("    USERS ||--o{ MODEL_HAS_PERMISSIONS : direct_permission")
add("    ROLES ||--o{ ROLE_HAS_PERMISSIONS : maps")
add("    PERMISSIONS ||--o{ ROLE_HAS_PERMISSIONS : maps")
add("```")
add("")

add("### Appendix — Roles × Permissions")
add("| Role | Cases | Hearings | Documents | Clients | Trash | Import/Export | Admin Tools |")
add("|---|---|---|---|---|---|---|---|")
add("| super_admin | CRUD | CRUD | view/upload/edit/delete | CRUD | view/restore/purge | full lifecycle | manage users/roles/audit/tools |")
add("| admin | CRUD | CRUD | view/upload/edit/delete | CRUD | view/restore/purge | full lifecycle | audit view, tools manage |")
add("| lawyer | view/create/edit | CRUD | view/upload | view/edit | — | — | — |")
add("| staff | view/create | view | view/upload | view/create | — | — | — |")
add("| client_portal | scoped view | — | — | — | — | — | — |")
add("")

add("### Appendix — Screen Inventory")
add("| Screen | Route | Purpose | Key Widgets | Filters | Columns/Fields | Actions |")
add("|---|---|---|---|---|---|---|")
add("| Dashboard | `/home` | KPIs, upcoming hearings/tasks | metric cards, upcoming list | role toggles | counts, timeline | module shortcuts |")
add("| Clients Index | `/clients` | Manage clients | search, pagination, locale toggle | status, cash/probono | client name EN/AR, contact lawyer, status, updated_at | view, edit, delete |")
add("| Client Detail | `/clients/{id}` | Client profile | tabbed related sections | N/A | client fields, related cases/contacts/documents | edit, delete, upload logo |")
add("| Cases Index | `/cases` | Browse matters | search, multi-select filters | status, degree, branch, client | matter names, client, status, next hearing, partner | view, edit, delete, manage opponents |")
add("| Case Detail | `/cases/{id}` | Matter hub | tabs (overview, hearings, tasks, documents, opponents) | opponent filter, timeline | case fields, related lists | edit, attach opponent, add hearing/task/document |")
add("| Hearings | `/hearings` | Manage sessions | calendar/list toggle, date picker | date range, lawyer, court | date, court, decision, next hearing | view, edit, delete |")
add("| Documents | `/documents` | Document repository | storage badges, signed downloads | storage type, client, case, doc type | document name, client, case, storage type, deposit_date | upload, download, inline, edit, delete |")
add("| Document Upload | `/documents/create` | Capture metadata & file | conditional file input, M-Files toggle | storage type | storage type, client, case, doc type, dates | save, cancel |")
add("| Admin Tasks | `/admin-tasks` | Track follow-ups | table with status badges | status, court, lawyer | required_work, status, performer, execution_date | view, edit, delete |")
add("| Admin Subtasks | `/admin-subtasks` | Granular steps | table list | next_date | performer, result, procedure_date | view, edit, delete |")
add("| Import Wizard | `/import` + steps | ETL pipeline | stepper, progress indicators | file status | session metadata, logs | upload, map, save choices, run, cancel |")
add("| Template Downloads | `/cases/import/template/...` etc. | Provide templates | action buttons | N/A | template descriptions | download |")
add("| Trash | `/trash` | Manage bundles | filter panel, bundle table | type, status, deleted_by | bundle id, root label, deleted_at, ttl, cascade_count | view, dry-run, restore, purge |")
add("| Trash Detail | `/trash/{uuid}` | Inspect bundle | accordions by entity, conflict summary | strategy selector | snapshot JSON summary | dry-run, restore, purge |")
add("| Data Quality Dashboard | `/data-quality` | Migration health | metric cards, progress bars | N/A | counts, referential integrity table | export CSV (planned) |")
add("| Audit Logs | `/audit-logs` | Review activity | filters for log name, user, date | log name, user | description, subject, causer, timestamp | view detail, export CSV |")
add("| Courts | `/courts` | Manage courts & circuits | forms with multi-select lookups | active flag | court names, circuits, floors, halls | create, edit, delete |")
add("| Opponents | `/opponents` | Manage opponents | search, pagination | active flag | opponent names, notes | create, edit, delete |")
add("| Option Sets Admin | `/admin/options` | Manage lookup sets | accordions for sets/values | none | set metadata, values table | add/edit/delete sets & values |")
add("| Import Profiles | `/admin/import/profiles` | Manage saved mappings | table list | target table | profile name, target table, updated_at | create, export, run |")
add("")

add("### Appendix — Authoritative DDL")
add("```sql")
add(ddl_text)
add("```")
add("")

add("### Acceptance Checklist")
add("- [ ] Implement MySQL schema exactly as defined (tables, indexes, constraints, enums).")
add("- [ ] Deliver bilingual fields & RTL layout with locale switching (EN/AR) and UTF-8 data handling.")
add("- [ ] Enforce RBAC permissions with roles/permissions matrix; protect trash/document operations and audit logging.")
add("- [ ] Implement validation rules mirroring Laravel FormRequests (dates, numeric ranges, MIME types, required_without pairs).")
add("- [ ] Build workflows: case intake, hearings, admin tasks, document lifecycle, trash restore/purge, ETL import wizard, data quality monitoring.")
add("- [ ] Implement screens with listed widgets, filters, columns, and actions; ensure pagination/search and signed document downloads.")
add("- [ ] Provide trash dry-run/restore/purge tooling and signed document downloads; maintain audit logs.")
add("- [ ] Support import templates, mapping, choice persistence, preflight validation, and idempotent reruns with reject handling.")
add("- [ ] Meet non-functional requirements (performance, security, localization, accessibility, hosting constraints).")
add("- [ ] Plan cron automation (trash purge, backups), extended APIs, finance modules, antivirus integration, and confirm lookup data completeness.")

OUTPUT_PATH.write_text("\n".join(parts), encoding="utf-8")

print(f"Generated {OUTPUT_PATH}")







